### ISSUE TITLE
disable trailing separator bar

### ISSUE THREAD

**Issue by CFenner** [glitch452/MMM-PlexNowPlaying#10]
Is there the ability to disable the trailing separator bar below the progress bar for the last item playing in the list? This looks a bit odd to me.

<img width="119" alt="Bildschirmfoto 2022-01-03 um 12 14 30" src="https://user-images.githubusercontent.com/9592452/147924501-943ef0d5-6c05-4d6e-aa25-56dc9357207a.png">

**Comment by glitch452** [comment]
Hi, yes, if you add the following css to your custom.css file, it should do the trick.
```css
.MMM-PlexNowPlaying .spacerRow:last-child {
	display: none;
}
```
